// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1yqw1xpB1dDWvvM8MEHv5EVKl_wqz8F8',
    appId: '1:837996528459:web:065aff67e983ad71985ece',
    messagingSenderId: '837996528459',
    projectId: 'mobi-esim',
    authDomain: 'mobi-esim.firebaseapp.com',
    storageBucket: 'mobi-esim.appspot.com',
    measurementId: 'G-9V35XLHRXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFpKFJx1jiX7j5YuY-a9_7rwTZycXf1U4',
    appId: '1:837996528459:android:34df25dbbb70b3ed985ece',
    messagingSenderId: '837996528459',
    projectId: 'mobi-esim',
    storageBucket: 'mobi-esim.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMxGCiQ0nvZskK8XatNxVD6ikXUNjZPIA',
    appId: '1:837996528459:ios:c36ad72472590edd985ece',
    messagingSenderId: '837996528459',
    projectId: 'mobi-esim',
    storageBucket: 'mobi-esim.appspot.com',
    iosBundleId: 'com.example.mobiEsim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMxGCiQ0nvZskK8XatNxVD6ikXUNjZPIA',
    appId: '1:837996528459:ios:238110690dfc5e79985ece',
    messagingSenderId: '837996528459',
    projectId: 'mobi-esim',
    storageBucket: 'mobi-esim.appspot.com',
    iosBundleId: 'com.example.mobiEsim.RunnerTests',
  );
}
